language: generic
os: linux
dist: bionic
# Dependency of the minted package
before_install:
    - sudo apt-get install texlive-full
install:
    - latexmk -pdf 00_master.tex
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Travis"
      - git config --local user.email "fstrobel@hm.edu"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
    provider: releases
    token: $GITHUB_TOKEN
    file: ./00_master.pdf
    cleanup: false
