language: generic
os: linux
dist: bionic

notifications:
  email:
    on_success: never
    on_failure: always
# Dependency of the minted package
jobs:
  include:
    - stage: Install
      before_install:
        - sudo apt-get install texlive-full
      install:
        - latexmk -pdf 00_master.tex
    - stage: deploy-develop
      if: branch = develop
      before_deploy:
            - git config --local user.name "Travis"
            - git config --local user.email "fstrobel@hm.edu"
            - export TRAVIS_TAG=daily-$(date +%Y%m%d)
            - git tag daily-$(date +%Y%m%d)
      deploy:
            provider: releases
            token: $GITHUB_TOKEN
            file: ./00_master.pdf
            cleanup: false
            on:
              all_branches: true
    - stage: deploy-master
      if: branch = master
      before_deploy:
            - git config --local user.name "Travis"
            - git config --local user.email "fstrobel@hm.edu"
            - export TRAVIS_TAG=release-$(date +%Y%m%d)
            - git tag release-$(date +%Y%m%d)
      deploy:
            provider: releases
            token: $GITHUB_TOKEN
            file: ./00_master.pdf
            cleanup: false
            on:
              all_branches: true
    - stage: deploy-tag
      if: tag IS present
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: ./00_master.pdf
        cleanup: false
        on:
          tags: true
