language: generic
os: linux
dist: bionic

cache:
  directories:
    - ./output

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: Install
      before_install:
        - sudo apt-get install texlive-full
      install:
        - latexmk -pdf main.tex
        - mv main.pdf ./output/bachelor-thesis.pdf
    - stage: deploy-develop
      if: branch = develop AND type = cron
      before_deploy:
        - git config --local user.name "Travis"
        - git config --local user.email "fstrobel@hm.edu"
        - export TRAVIS_TAG=daily-$(date +%Y%m%d)
        - git tag daily-$(date +%Y%m%d)
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file: ./output/bachelor-thesis.pdf
        skip_cleanup: true
        on:
          all_branches: true
    - stage: deploy-tag
      if: tag IS present
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: ./output/bachelor-thesis.pdf
        skip_cleanup: true
        on:
          tags: true
